### ISSUE TITLE
Validation is skipping over lines and scholia

### ISSUE THREAD

**Issue by scnevi17** [homermultitext/hmt-utils#41]
urn:cite:hmt:msA.244r

When validating this page, lines 257, 263, 266, and 270 are skipped over. Lines 263 and 270 are both lines that have tags, one a place tag and one and ethnic tag, and these tags are not accounted for in the lists of places and ethnics peoples when the system parses it. We did not find a problem with the indexing. We do not know if if this has been occurring on other folios as well.

Entire scholia have also been skipped over as well.

Missing scholia:

Main scholia: 18.92, 93, 94, 95, 96
Interior: 18.24,25
Intermarginal: all

**Comment by scnevi17** [comment]
This issue extends beyond 244r.  It applies to all validation on Iliad 18.  We attempted validation on multiple virtual machines to ensure that it was not an error with just one machine.  This failed.  We also attempted to validate on an unrefreshed vm, which produced the same errors.  Previous validation (of 239r, at the least) analyzed all the text on the page when we began validation early this week, but today's re-validation of 239r yielded truncated results.

**Comment by neelsmith** [comment]
fixed.

**Comment by scnevi17** [comment]
We attempted to validate Book 18 again but we still have the same issue as last time. We pulled in git and refreshed. We began with 239r, and tried a couple of subsequent pages, but the validation still skipped over lines of main text and many of the scholia. Also, on 239r, all three of the words that were marked incorrect under the lexical token page are words that have already been added to the byzortho repository.

We then tried to validate Book 15, again pulling in git and refreshing, but the validation still did not account for all of the main text and much of the scholia, skipping over all of the main scholia on the two first pages we looked at (191r, 191v).

In all of the folios that we tried to validate, it accounted for less than 200 lexical tokens on each folio, which is much less than on the first day we validated last week.
